jobs:
  analyse_js:
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: .
      - rn/yarn_install
      - run:
          command: yarn eslint
          name: Run ESLint
      - run:
          command: yarn tsc
          name: Typescript
      - run:
          command: yarn jest
          name: Jest
  checkout_code:
    executor:
      name: rn/linux_js
    steps:
      - checkout
      - persist_to_workspace:
          paths: .
          root: .

orbs:
  rn: react-native-community/react-native@5.1.0
version: 2.1
workflows:
  test:
    jobs:
      - checkout_code
      - analyse_js:
          requires:
            - checkout_code